abstract: Failover and Load Balancing of DBI Handles
author: Dan Wright <dwright@cpan.org>
build_requires: 
  Pod::Simple: 0
  Test::More: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
name: DBD-Multi
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0.19
  perl: 5.005
version: 0.02
