name: DBD-Multi
version: 0.10
abstract: Failover and Load Balancing of DBI Handles
author: Dan Wright <dwright@cpan.org>
license: perl
distribution_type: module
build_requires:
  Test::Pod::Coverage: 1.04
  Test::Pod: 1.14
  Pod::Simple: 0
  Test::More: 0
requires:
  perl: 5.005
  Class::Accessor::Fast: 0.19
  Sys::SigAction: 0.1
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
