name: DBD-Multi
version: 0.01
abstract: Failover and Load Balancing of DBI Handles
author: Dan Wright <dwright@cpan.org>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
  DBD::SQLite: 0
requires:
  perl: 5.005
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
